const exampleWriting = [
  {
    id: 'example-writing',
    type: 'writing',
    headerImage: {
      image: 'https://i.imgur.com/cRSW6ar.jpg',
      alt: 'A description of the header image.',
    },
    images: {
      0: {
        image: 'https://i.imgur.com/cRSW6ar.jpg',
        alt: 'A description of the header image.',
      },
      4: {
        image: 'https://i.imgur.com/cRSW6ar.jpg',
        alt: 'A description of the header image.',
      },
      8: {
        image: 'https://i.imgur.com/cRSW6ar.jpg',
        alt: 'A description of the header image.',
      },
      12: {
        image: 'https://i.imgur.com/cRSW6ar.jpg',
        alt: 'A description of the header image.',
      },
    },
    audioLink: '',
    text: {
      title: 'Episode Number - Game Title',
      date: '10 January 2010',
      summary:
        "There's a lot to commend about <a href='https://www.pixelvision.net'>Pixel Vision</a> , particularly given that it was released in 2014. Playing it now, I'm conscious there are another 6 years of gaming developments skewing my reactions and assumptions and watering down its achievements. That said, I want to convey how it feels to play today, not reiterate how impressive it might have been for its time.",
      body: [
        `There's a lot to commend about Alien: Isolation, particularly given that it was released in 2014. Playing it now, I'm conscious there are another 6 years of gaming developments skewing my reactions and assumptions and watering down its achievements. That said, I want to convey how it feels to play today, not reiterate how impressive it might have been for its time.`,
        `This review eschews comparison to the Alien films, since the game ought to stand on its own, but for context: the player assumes the role of Amanda Ripley, Ellen Ripley's daughter, who is determined to learn what happened to her mother after her vessel, the Nostromo, went missing. Amanda joins the crew of a new ship, the Torrens, and heads to the Sevastopol space station in search of the Nostromo flight recorder and other clues. Unsurprisingly, chaos has unfolded there, and - spoiler alert! - the Alien is onboard wreaking havoc.`,
        `The game starts aboard the Torrens, but you're not there for long before you arrive at Sevastopol. First impressions on pretty much every front are positive. The graphics stand up fairly well, they're obviously not recent, but they're not particularly bad either. Edges are angular and textures quite flat, but not enough to distract from the overall sense of the place, which is clearly in the aftermath of a riot or uprising. Graffiti is sprayed across walls, windows are smashed, more or less everything is broken, on fire, or without power, and the few people encountered are freaking out, attacking one another or running in panic. It's immediately creepy and immersive.`,
        `Beyond the unsettling visuals, an intricate weave of sound design contrives to stir unease too, with crackling radio comms, distant banging and a sinister orchestral sound bed. The audio is without a doubt one of the game's fortes, and listening through headphones, it utterly envelopes you, giving directional cues to threats and - thank God - to save points. But it's also a card they overplay a little bit, with swelling music often forecasting action sequences and sudden violin screeches provoking artificial jumpscares. It can be misleading too, manufacturing a sense of imminent peril when perhaps you're actually in a safe area, or emphasising the Alien pounding around in vents when it's not nearby. It's a kind of sleight of ear that is initially engaging, but begins to feel duplicitous. The game doesn't really utilise silence either, which is surprising in a horror, although one could argue the setting would never afford the opportunity.`,
        `One minor gripe I have with Alien: Isolation's aesthetic is that the technology aboard the spaceships is backward even by today's standards. This is a retro future, and clearly a deliberate design choice, with the game developers imitating the original 1979 film's set and setting. It's fine up to a point, but strange given the year is 2137 and we've colonised outer space. The much more recent Prometheus was happy enough to advance the technology a bit (despite being a prequel), and new audiences who may not have seen the films are likely to be baffled at the incongruity. The computer terminals all seem to be using graphics cards from the late 1980s/ early 90s, with a UI closer to DOS than anything resembling a modern computer and mechanical keyboards. There are audio tapes left scattered around as well which add a bit of colour to the plot, but again, anachronistically, these are in players that contain visible reels of tape, with chunky play, stop, and rewind buttons. Remarkable that playing audio requires such a huge device, yet Amanda spends half her time dodging synthetic AIs - pre-programmed robots that look and act pretty similarly to humans (while falling firmly into uncanny valley). This juxtaposition of futuristic and borderline archaic doesn't feel cyberpunk dystopian, just jarring.`,
        `Throughout the game, you'll find resources scattered, items with vague, ambiguous names like sensor, bonding agent, scrap metal and compound B. These can then be used to construct usable items like pipe bombs, EMP mines, flashbangs and 'noise makers' (because none of the aforementioned make a sound??!). While resources are fairly prevalent, the crafting mechanic itself is basic enough that it's arguably superfluous, and an equally effective and less distracting approach would have been just to distribute the items themselves. There are some thematic inconsistencies with crafting, too, like why does a molotov cocktail require a sensor?`,
        `It's speedily evident that your search for Ellen Ripley is little more than a mcguffin to get you started, as once aboard Sevastopol and introduced to the Alien, the story shifts focus to simply surviving as you make your way through the space station chasing objectives which enable you to escape it again. This story development is serviceable enough, though lots of missions boil down to tried and tested objectives like 'turn on power', or 'unlock door'. Mostly this is pretty rote stuff and no more egregious than in any other game, but some mission prompts are particularly loose, if not borderline nonsensical:`,
        `‘I've got a plan to trap the Alien, get in a transit car and meet Ricardo at the tower, I'll coordinate from here,’ says the station marshall at one stage, and Ripley jumps to obey. But why? It felt entirely implausible. My own reaction was, 'how about you tell me the plan now, so I can go into it prepared?' Ripley, on the other hand, does as she's told, enabling a predictable twist she could have foreseen with a few obvious follow-up questions. Why would anyone throw themselves into grave danger before establishing what it is they intend to do there?`,
        `Similarly, Mission 9, a playable flashback sequence where you control a salvager exploring The Derelict (a crashed alien craft), offers almost nothing to the player and breaks so many rules of good game design. The entire level is set during a storm on a dusty, rocky planet, with visibility obscured to nearly zero. It's completely linear, and I mean, there are literally boulders on either side of the you at all times to prevent movement off the set path. The colour palette is extremely limited, though there's nothing interesting to look at anyway. The game devs use your cumbersome exosuit as an excuse to enforce walking for the entire duration of the mission - force walking! Seriously! - and you're required to double back on yourself and repeat sections of the environment you've already explored. The very moment something interesting happens, it turns to a cut scene and ends the flashback. The whole thing takes too long, feels uncomfortably awkward to control, and adds nothing to the overall experience of Alien: Isolation.`,
        `The Alien itself is a clever game mechanic, but also a source of many of the issues with the game. The AI behind its predation has been much lauded, utilising all sorts of techniques so it gets smarter as you play, allegedly learning your hiding places and tactics to make you keep adapting. An interesting analysis and explanation of how this works can be read here. There's a balance between developing a clever, ever-ominous Alien though, and allowing the player to feel safe enough to actually enjoy the time they spend in the game world. Personally, I felt the Alien either menaced you too much, appearing in places and at times that were unreasonable, or not enough. For example, a gun shot would almost inevitably summon it within a few seconds, and yet a crashing lift shaft in its nest? Nada. Further, I found myself so fixated on the incessant risk of dismemberment, of where the Alien might be and how vulnerable I was, that I was barely able to explore the ship properly and appreciate the detailed environments. After once being slaughtered while accessing a terminal for instance, for ever after, reading emails and listening to audio logs was an urgent endeavour. Often I ended up scanning text for mission critical information like passcodes rather than taking the time to read carefully and understand how these communications fleshed out the plot.`,
        `Compounding this dilemma is the fact that save points are sometimes so sparsely located. Although nothing relative to Dark Souls or Sekiro, finding yourself caught out by the Alien at a critical juncture and forced to reload can still mean replaying a tedious passage of unlocking doors, torching open vents or whatever else, only to find yourself ambushed again at the same point. Save points also have a built in timer so they can't be reused too frequently, generally a cunning mechanic to ramp up the tension, but sometimes just plain annoying. Re-looting rooms over and over because you too cautiously saved beforehand is a bore.`,
        `Sometimes the AI mechanism of the Alien which is meant to make it learn your playstyle, enables it to find you repeatedly, no matter how you behave or what distractions you fire off. This was particularly galling in one section of my playthrough when I needed to unlock a door with the 'autotuner' (a mini-game which takes about 10 seconds), and no matter what I did to distract the Alien beforehand, it always emerged from a vent directly above the door exactly as I was entering the animation to unlock it. I reloaded this section of the game more times than any other, even though in theory, it ought to have been easy to progress. Such moments generate the kind of frustration that prompt rage quits and break controllers.`,
        `Other enemies on Sevastopol are practically benign in comparison to the tenacious, haunting, single-mindedness of the Alien. Hostile humans are few and far between and easy enough to dispatch when you encounter them anyway, and Working Joes - the synthetic androids who march everywhere with glowing red eyes asking, 'Something amiss?' - are slow and can either be executed (noisily) with stun tactics, or often avoided entirely. Even when they catch you, the game gives you an option to wriggle free and escape, and they don't do much damage anyway. The levels where you aren't hunted by the Alien (and thank God, there are a few), provide respite from the tension and make the game a little more conventional in style: finally enabling you to explore corridors at your own pace and figure out your route with as much trial and error as necessary. The only other serious threat, and these are irritating rather than terrifying, are the baby Alien 'face huggers', which will kill you immediately if they attach themselves to you and are surprisingly difficult to see coming and aim at.`,
        `Whether you enjoy Alien: Isolation will ultimately boil down to your tolerance for survival horror and indefatigable, undefeatable enemies. Where Resident Evil and the Dead Space series threw horrors at you and gave you the armaments to triumph over them, giving a pattern of tension and release, playing through Alien is to play through a shroud of endless discomfort, an unlifting fog of doubt about whether the Alien is around the next corner, in the next vent, behind the next set of doors.`,
        `Alien: Isolation will present challenges that seem insurmountable, but with a combination of persistence and luck, you'll stumble through if you keep trying hard enough, and it's rewarding in the end. In some ways, this is a flaw with all games depicting a survivor fighting tooth and nail through hell to make it out the other side. They never are survivors. The game forces you to die over and over, and it's only through Edge of Tomorrow-like tactics and resilience and Groundhog Day zen that you are able to triumph (relatively) unscathed. Yet, despite knowing things are only ever as bad as your last save, when all's said and done, Alien: Isolation is an intense experience, and certainly a riveting one, an accomplishment that despite its many flaws, has to be considered a success.`,
        `Finishing at last, I recalled a moment early on when I first picked up the flame thrower, how the game advised that the Alien would briefly flee if bathed in fire, and how I complacently thought to myself, 'huh, who needs a flamethrower? I've dodged it easily enough this far.' Now I sit trembling, both rueful and gleeful at my naivety. What a journey it's been.`,
      ],
      audioExtracts: [],
      clarifications: [],
      contentWarning: [],
    },
    comments: [],
  },
];

export default exampleWriting;
